# sympy 和 numpy矩陣筆記
### 安裝
- pip install numpy
- pip install sympy

確認安裝

In [1]:
import numpy as np
import sympy as sp
print("numpy version {} \nsympy version {}".format(np.__version__,sp.__version__))

numpy version 1.14.0 
sympy version 1.1.1


## numpy


In [2]:
#矩陣a 用雙層array創建
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
#結合arrays組成一個雙層array
b =np.c_[np.array([1,2,3]), np.array([4,5,6]),np.array([7,8,9])]
print("matrix a \n{} \nmatrix b\n{}".format(a,b))


matrix a 
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
matrix b
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Matrix 運算 
- 加法a+b
- 乘法a@b

In [3]:
print("a+b \n{} \na*b \n{}".format(a+b,a@b))

a+b 
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]] 
a*b 
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [4]:
# 單位矩陣
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# sympy

In [6]:
#定義兩個矩陣
c = sp.Matrix([[1,2,3], [4,5,6], [7,8,9]])
d = sp.Matrix([[9,8,7,4,5,6,1,2,3]])

### Matrix 運算 

- 加法a+b
- 乘法a*b

In [7]:
c+d

Matrix([
[10, 10, 10],
[ 8, 10, 12],
[ 8, 10, 12]])

In [8]:
c*d

Matrix([
[ 20,  24,  28],
[ 62,  69,  76],
[104, 114, 124]])

# sympy 各種強大的矩陣函式

In [9]:
# 單位矩陣
sp.eye(2,4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0]])

In [10]:
# 0矩陣
sp.zeros(3,6)

Matrix([
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]])

In [11]:
# row互換
c.row_swap(2,0)
c

Matrix([
[7, 8, 9],
[4, 5, 6],
[1, 2, 3]])

In [12]:
# column互換
c.col_swap(1,0)
c

Matrix([
[8, 7, 9],
[5, 4, 6],
[2, 1, 3]])

In [13]:
# 得到特定的row
c.row(1)

Matrix([[5, 4, 6]])

In [14]:
# 特定的column
c.col(-1)
# 參數為-1時取最後一行

Matrix([
[9],
[6],
[3]])

In [15]:
# 刪除特定row or column
c.col_del(0)
c

Matrix([
[7, 9],
[4, 6],
[1, 3]])

In [16]:
c.row_del(2)
c

Matrix([
[7, 9],
[4, 6]])

In [17]:
# 插入在特定的行or列
c = c.row_insert(2, sp.Matrix([[8, 9]]))# insert row時 為兩層的array
c

Matrix([
[7, 9],
[4, 6],
[8, 9]])

In [18]:
c = c.col_insert(0, sp.Matrix([1,4,7]))# insert col時 為ㄧ層的array
c

Matrix([
[1, 7, 9],
[4, 4, 6],
[7, 8, 9]])

In [19]:
#轉置矩陣
c.T

Matrix([
[1, 4, 7],
[7, 4, 8],
[9, 6, 9]])

In [20]:
#得到reduce row echelon form 第二個回傳值是主元位置的列表
c.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [21]:
#c矩陣平方
c**2

Matrix([
[ 92, 107, 132],
[ 62,  92, 114],
[102, 153, 192]])

In [22]:
# M的反矩陣
M = sp.Matrix([[1,2,5], [-2,3,4],[1,1,1]])
M ** -1

Matrix([
[1/14, -3/14,  1/2],
[-3/7,   2/7,    1],
[5/14, -1/14, -1/2]])